### ISSUE TITLE
keymesh addon delete blend shapes

### ISSUE THREAD

**Issue by project100man** [pablodp606/keymesh-addon#10]
Creating a key frame on a mesh with a blendshape will remove the blendshape.

**Comment by aldrinmathew** [comment]
@project100man
Can you provide the exact steps followed while performing the action? Either textually, or in the form of a video?
Hopefully I can fix this in my fork of the addon.

**Comment by project100man** [comment]
https://www.youtube.com/watch?v=LfXNQhTSmkE
I use 
Windows 10
Dell G7 7790
Blender 2.92.100.0 from Microsoft store (Splash screen shows 2.92.0...this is another bug???)

**Comment by project100man** [comment]
I try Keymesh0.1 and 0.12.
Both Keymesh addon destroys blend shape.

**Comment by aldrinmathew** [comment]
@project100man 
Thanks for the video. I got what you meant.

### Problem
Shape Keys are not compatible with Keymesh by design. The problem is that Shape keys depend completely on the mesh data and the vertices and their positions. Keymesh creates new mesh data everytime you use it. Which means retaining Shape Keys and it's data is pointless since the mesh data is changed.
This is also why there is no interpolation between Keymesh keyframes, which is why Mesh Data is changed instantly, instead of gradually achieving it.

### Fix?
There is potential for a minor fix: To retain shape keys and it's settings when Keymesh is used. But then, once you change the new Mesh by adding or deleting vertices, or Remesh or any sort of changes that usually doesn't work with Shape Keys, this will no more be useful. Also, if new shape keys are added, then it will have to be added for each of the Meshes created by Keymesh, when the other meshes might not have the same mesh data as the current one. This could make the mesh data corrupted or invalid.
